name: job_scraper
channels:
  - plotly
  - anaconda
  - conda-forge
dependencies:
  - pandas=2.2.2 
  - selenium=4.19.0
  - fake-useragent=1.4.0
  - beautifulsoup4=4.12.2
  - python=3.12.3
  - chromedriver-autoinstaller=0.6.4
